---
title: "Run_A_Day"
author: "Emmett & Rachel"
format: pdf
editor: visual
---

## Running a Singular Day

##### This will allow the simulation to replicate and find sample statistics for the optimization.

```{r}
#load libraries
library(tidyverse)
```

NOTE: THIS CODE CHUNK IS NOT FOR INCLUSION IN FINAL FUNCTION. THIS IS FOR CURRENT WORKING DOCUMENT, SO THAT WE HAVE REASONABLE INPUT DATAFRAMES TO WORK FROM IN THE MEANTIME.

```{r}
#create dummy arrival rates data set 
bike_data<-read.csv('/Users/juliadubnoff/Downloads/sample_bike.csv')
bike_data<-bike_data_clean(bike_data)

estimate_arrival_rates <- function(data) {
    data <- data %>%
    mutate(
      start_time = as.POSIXct(start_time, format = "%Y-%m-%d %H:%M:%S"),
      end_time   = as.POSIXct(end_time,   format = "%Y-%m-%d %H:%M:%S")
    )
  
  # compute the average number of trips per hour between each pair
  x_hat <- data %>%
    mutate(hour = hour(start_time)) %>%
    filter(start_station != "R", end_station != "R") %>%
    group_by(start_station, end_station, hour) %>%
    summarise(avg_trips = n() / n_distinct(as_date(start_time)), 
              .groups = "drop") 
  
  # pivot longer to get change in count 
  data$end_station <- as.character(data$end_station)
  trips_long <- data %>%
    pivot_longer(cols = c("start_station", "start_time", 
                          "end_station", "end_time"),
                names_to = c("type", ".value"),   
                names_pattern = "(start|end)_(.*)") %>%
    mutate(change = ifelse(type == "start", -1, 1),
           hour = hour(time)) %>%
    select(station, time, hour, change)
  
  # add hour markers so we can get cumulative time
  dates <- unique(as_date(trips_long$time))
  hours <- c(seq(0,23,1),seq(0,23,1)+0.9999999)
  stations <- unique(trips_long$station)
  hr_pts <- expand.grid(time = dates, hour = hours, 
                        station = stations) %>%
    mutate(time = as.POSIXct(time) + hour*60*60,
           hour = hour(time))
  hr_pts$change <- 0
  trips_long <- rbind(trips_long, hr_pts)
  
  # find average availability 
  alpha_hat <- trips_long %>%
    group_by(station) %>%
    filter(station != "R") %>%
    arrange(time) %>% 
    mutate(count = cumsum(change),
           date = as_date(time)) %>%
    group_by(station, hour, date) %>%
    summarize(time_avail = 
                sum(difftime(time, lag(time), units="hours")*(count > 0), 
                  na.rm = TRUE)) %>%
    summarize(avg_avail = mean(time_avail)) %>%
    mutate(avg_avail = round(as.numeric(avg_avail), digits = 4)) %>%
    ungroup()
  
  # join the data and compute arrival rates
  mu_hat <- x_hat %>%
    left_join(alpha_hat, by = c("start_station" = "station", "hour")) %>%
    mutate(mu_hat = ifelse(avg_avail > 0, avg_trips / avg_avail, NA))
  
  return(mu_hat)
}


# Estimate arrival rates
arrival_rates <- estimate_arrival_rates(bike_data)





#create dummy bike placement data set
bike_placement<-bike_data%>%
  group_by(end_station)%>%
  summarize(bikes_to_start=5)%>%
  rename(station=end_station)
  

```

**Function:**

```{r}

run_a_day<-function(arrival_rates_df, bike_placement){
  
  arrival_rates_df<-arrival_rates_df%>%
    group_by(start_station, end_station)%>%
    summarize(lambda_max=max(mu_hat))

  
  
  
  
  
  return(unhappy_customers, times_unstocked)
  

}





```
